jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
        json_serialization:
            options:
                - JSON_UNESCAPED_SLASHES
                - JSON_PRESERVE_ZERO_FRACTION
    default_context:
        serialization:
            serialize_null: true