name: test
env:
  STAGE: dev
on:
  push:
    branches-ignore:
         - master
jobs:
  code-analyse:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          coverage: none
          tools: phpcs

      - name: Set up ENV
        run: echo "APP_ENV=${ env.STAGE }" >> $GITHUB_PATH/.env.local

      - name: Install dev PHP dependencies
        if: ${{ env.STAGE == 'dev' }}
        run: |
          composer install --dev --prefer-dist --no-progress --no-ansi --no-interaction
          echo "${PWD}/vendor/bin" >> $GITHUB_PATH

      - name: Install prod PHP dependencies
        if: ${{ env.STAGE == 'prod' }}
        run: |
          composer install --prefer-dist --no-progress --no-ansi --no-interaction
          echo "${PWD}/vendor/bin" >> $GITHUB_PATH

      - name: Run lint
        uses: wearerequired/lint-action@v2
        with:
          php_codesniffer: true
